server:
  port: 8001

spring:
  datasource:
    url: jdbc:h2:mem:myuserdb
    username: na
    password: password
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
